### ISSUE TITLE
[Request]  Figma

### ISSUE THREAD

**Issue by Hexality** [terrapkg/packages#1534]
**What software are you requesting to be packaged?**
> The name of the software and link to website (if it exists) and source code (if available).

[Figma](https://github.com/Figma-Linux/figma-linux/) `(https://github.com/Figma-Linux/figma-linux/)`

**Describe the motivation**
> A clear and concise description of why you want this package. Would this provide value to other users?

This would be a better way of managing updated for Figma for Linux as the normal package is kind of a pain to manage and many people use it. Yeah, the flatpak version do exist, but just like IDEs it doesn't work well specially with drag/drop without enabling "access filesystem access" permission anyways, so why even bother with flatpak when the native unsandboxed version already exists?!

**Additional context**
> Add any other context about the package request here.

Figma is a design tool with the purpose of being a help hand for UX/UI designers to sketch and build UI concepts for hobby and mass production.

**Comment by madonuko** [comment]
After some thorough discussions and internal debates, I think it is safe to say we probably will not add Figma into Terra for the following reason:

As you may know, our submission policy clearly states that:
> Please refrain from submitting applications that work perfectly fine as a Flatpak, unless there is a technical or UX justification for it. Examples of these exceptions are: 

This statement is worded in a confusing way; what this really means is that you may submit applications
- if there is a **limitation in Flatpak itself** that causes the application to not work well as a Flatpak; or
- the application does not work well with the Flatpak model; e.g. it should not be sandboxed.

Otherwise, the submission will most likely be rejected.

Your argument
> just like IDEs it doesn't work well specially with drag/drop without enabling "access filesystem access" permission anyways

unfortunately does **not** meet the requirements stated in the policy (as aforementioned) because 'not enabling "access filesystem access" permission by default' is not a Flatpak limitation; but instead a Flatpak packaging issue. You should report this to the Flatpak packager in order to mitigate this issue properly.

**Comment by Hexality** [comment]
The reason for refusal of the propose makes no sense as, just like I said, it doesn't work well nor correctly on the flatpak sandbox. It's not just a packaging problem, its a overall problem that happens with almost every software that works with graphics or code, and its not different when it comes to figma.

**Comment by nothingneko** [comment]
This is a problem that should be dealt with by the Figma Flatpak maintainers and not by us repackaging it again. This functionality is 100% possible in Flatpak and is either an issue with Figma-Linux itself or their Fllatpak config. Please file an issue with Figma-Linux, and if they affirm that this is not possible within the bounds of their app then we can reconsider.

Thank you.
