### ISSUE TITLE
OpenAsar Canary broken on tauOS/Silverblue

### ISSUE THREAD

**Issue by lleyton** [terrapkg/packages#61]
**Describe the bug**
openasar-canary doesn't install properly when using an rpm-ostree based distribution like tauOS

**To Reproduce**
1. Install `openasar-canary`
2. Open Discord Canary

**Expected behavior**
OpenAsar should be loaded

**Affected (please complete the following information):**
 - Distro tauOS, Fedora Silverblue
 - Package openasar-canary

**Additional context**
Currently, we install openasar-canary using a trigger scriptlet. These are [not currently supported](https://github.com/coreos/rpm-ostree/issues/1180) by rpm-ostree. We'll need to figure out a way around this.

**Comment by getchoo** [comment]
maybe we could just make a second or split package that replaces `app.asar` during `%install`. this would also solve a possible issue i've noticed in the current package, which is that when `openasar-canary` is removed, the modified `app.asar` is not due to the lack of a `%postun`. it could also make the package easier to install imo, since currently you need to install `openasar-canary` and *then* `discord-canary`, which isn't super intuitive and not apparent unless reading the spec file

**Comment by lleyton** [comment]
I'm a bit confused, would this package bundle `discord-canary` but with the modified `app.asar`?

**Comment by getchoo** [comment]
no, it could be a subpackage or completely separate package (on second thought the later would probably be easiest) named something like `discord-canary-openasar` that would bundle the modified asar. the `discord-canary` package would remain the same

**Comment by lleyton** [comment]
ahh, gotcha. I'll have this issue up for grabs then :P
