### ISSUE TITLE
[FYRA-354] Potential deprecation of Vesktop (vencord-desktop)

### ISSUE THREAD

**Issue by lleyton** [terrapkg/packages#886]
We're considering deprecating the Vesktop package, as a reasonably well maintained Flatpak exists, which seems to act functionally the same as our RPM version. Is there something we're missing?

<sub>[FYRA-354](https://linear.app/fyra/issue/FYRA-354/potential-deprecation-of-vesktop-vencord-desktop)</sub>

**Comment by madonuko** [comment]
obsolete?

**Comment by PoorPocketsMcNewHold** [comment]
I would agree that it's obsolete. The project isn't named "vencord-desktop" anymore, and the Tera proposed version is pretty old "0.4.4" instead of the current "1.5.2", 0.4.4 date back from november 2023.
https://github.com/Vencord/Vesktop The project automatically build .rpm packages in aarch64 and x86_x64 format *(Thought, they seems to be lazily automated as it create conflicting artifact issues with lib caches files, and other electron apps, like the ProtonMail app)*
